on:
  push:
    tags:
    - 'v*'

name: Cross-compile and release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  # https://github.com/japaric/rust-cross#the-target-triple
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
        - wasm32-unknown-emscripten
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        name: Upload built binary
        with:
          name: built-binary
          path: .next/
  release:
    name: Release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifacts
        with:
          name: built-binary
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
      - name: Create release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - First change
            - Second change
          draft: false
          prerelease: false
      - name: Upload 64-bit Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./client.exe
          asset_name: client-x86_64-pc-windows-gnu-${{ steps.version.outputs.full }}.exe
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 64-bit Linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./client
          asset_name: client-x86_64-unknown-linux-gnu-${{ steps.version.outputs.full }}
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 32-bit WebAssembly build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./client.wasm
          asset_name: client-wasm32-unknown-emscripten-${{ steps.version.outputs.full }}.wasm
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
