on:
  push:
    tags:
    - 'v*'

name: Cross-compile and release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
      - name: Create release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - First change
            - Second change
          draft: false
          prerelease: false
  build:
    name: Build
    needs: [ release ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  # https://github.com/japaric/rust-cross#the-target-triple
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
        - i686-unknown-linux-gnu
        - i686-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Upload release asset
        id: upload_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.new_release.outputs.id }}
          assets_path: target/release/client.*
