on:
  push:
    tags:
    - 'v*'

name: Cross-compile and release

env:
  PROGRAM_NAME: client

jobs:
  build:
    name: Build ${{ matrix.rust-toolchain }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  # https://github.com/japaric/rust-cross#the-target-triple
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
        # - wasm32-unknown-emscripten  # Seems to have problems, look into later
        rust-toolchain:
        - stable
        - nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target }}
          toolchain: ${{ matrix.rust-toolchain }}
      - name: Install build dependencies
        if: ${{ contains(matrix.target, 'linux') }}
        run: sudo apt-get install libfontconfig libfontconfig1-dev
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Cross build
        run: cross build --target ${{ matrix.target }} --release
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: built-binary
          path: |
            !target/${{ matrix.target }}/release/*.pdb
            !target/${{ matrix.target }}/release/*.d
            target/${{ matrix.target }}/release/${{ env.PROGRAM_NAME }}*
  release:
    name: Release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.2.1
        name: Download artifacts
        with:
          name: built-binary
      - uses: nowsprinting/check-version-format-action@v4
        id: version
        with:
          prefix: 'v'
      - name: Check for pre-release
        uses: haya14busa/action-cond@v1
        id: is_prerelease
        with:
          cond: ${{ steps.version.outputs.prerelease != '' }}
          if_true: true
          if_false: false
      - name: Create release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.value }}
      - name: Upload 64-bit Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}.exe
          asset_name: ${{ env.PROGRAM_NAME }}-x86_64-pc-windows-gnu-${{ steps.version.outputs.full }}.exe
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 64-bit Linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}
          asset_name: ${{ env.PROGRAM_NAME }}-x86_64-unknown-linux-gnu-${{ steps.version.outputs.full }}
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 32-bit WebAssembly build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}.wasm
          asset_name: ${{ env.PROGRAM_NAME }}-wasm32-unknown-emscripten-${{ steps.version.outputs.full }}.wasm
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
        continue-on-error: true
