on:
  push:
    tags:
    - 'v*'

name: Cross-compile and release

env:
  PROGRAM_NAME: client

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:  # https://github.com/japaric/rust-cross#the-target-triple
        - x86_64-unknown-linux-gnu
        - x86_64-pc-windows-gnu
        - wasm32-unknown-emscripten
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        name: Upload built binary
        with:
          name: built-binary
          path: |
            !target/${{ matrix.target }}/release/*.pdb
            !target/${{ matrix.target }}/release/*.d
            target/${{ matrix.target }}/release/${{ env.PROGRAM_NAME }}*
  release:
    name: Release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifacts
        with:
          name: built-binary
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
      - name: Check for pre-release
        uses: haya14busa/action-cond@v1
        id: is_prerelease
        with:
          cond: ${{ steps.version.outputs.prerelease != '' }}
          if_true: true
          if_false: false
      - name: Create release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.value }}
      - name: Upload 64-bit Windows build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}.exe
          asset_name: ${{ env.PROGRAM_NAME }}-x86_64-pc-windows-gnu-${{ steps.version.outputs.full }}.exe
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 64-bit Linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}
          asset_name: ${{ env.PROGRAM_NAME }}-x86_64-unknown-linux-gnu-${{ steps.version.outputs.full }}
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
      - name: Upload 32-bit WebAssembly build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./${{ env.PROGRAM_NAME }}.wasm
          asset_name: ${{ env.PROGRAM_NAME }}-wasm32-unknown-emscripten-${{ steps.version.outputs.full }}.wasm
          asset_content_type: application/zip
          upload_url: ${{ steps.new_release.outputs.upload_url }}
